local_backend: true

media_folder: "public/images"

backend:
  name: git-gateway
  branch: main
collections:
  - name: "cv"
    label: "Curriculum Vitae"
    files:
      - label: "CV in english"
        name: "cv-en"
        file: "./cv-en.json"
        format: "json"
        extension: "json"
        fields:
          - label: "Basics"
            name: "basics"
            widget: "object"
            fields:
              - {label: "Full name", name: "name", widget: "string"}
              - {label: "Headline", name: "label", widget: "string"}
              - {label: "Profile photo", name: "image", widget: "string", hint: "Paste an URL"}
              - {label: "Summary", name: "summary", widget: "text"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Phone number", name: "phone", widget: "string", required: false}
              - {label: "Website", name: "url", widget: "string", required: false}
              - label: "Location"
                name: "location"
                widget: "object"
                fields:
                  - {label: "Address", name: "address", widget: "string", required: false}
                  - {label: "Postal code", name: "postalCode", widget: "string", required: false}
                  - {label: "City", name: "city", widget: "string", required: false}
                  - {label: "Country Code", name: "countryCode", widget: "string", default: "MX", required: false}
                  - {label: "Region", name: "Region", widget: "string", default: "Mexico"}
              - label: "Profiles"
                name: profiles
                widget: "list"
                fields:
                  - {label: "Network", name: "network", widget: "string"}
                  - {label: "Username", name: "username", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
                    

